package cn.lcf.ims.mapper;

import cn.lcf.ims.condition.ApplicationCondition;
import cn.lcf.ims.entity.Application;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface ApplicationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application
     *
     * @mbg.generated Mon Jan 02 19:26:45 GMT+08:00 2017
     */
    @Delete({
        "delete from application",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application
     *
     * @mbg.generated Mon Jan 02 19:26:45 GMT+08:00 2017
     */
    @Insert({
        "insert into application (id, name, ",
        "code, description, ",
        "base_path)",
        "values (#{id,jdbcType=INTEGER}, #{name,jdbcType=VARCHAR}, ",
        "#{code,jdbcType=VARCHAR}, #{description,jdbcType=VARCHAR}, ",
        "#{basePath,jdbcType=VARCHAR})"
    })
    int insert(Application record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application
     *
     * @mbg.generated Mon Jan 02 19:26:45 GMT+08:00 2017
     */
    @InsertProvider(type=ApplicationSqlProvider.class, method="insertSelective")
    int insertSelective(Application record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application
     *
     * @mbg.generated Mon Jan 02 19:26:45 GMT+08:00 2017
     */
    @Select({
        "select",
        "id, name, code, description, base_path",
        "from application",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="code", property="code", jdbcType=JdbcType.VARCHAR),
        @Result(column="description", property="description", jdbcType=JdbcType.VARCHAR),
        @Result(column="base_path", property="basePath", jdbcType=JdbcType.VARCHAR)
    })
    Application selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application
     *
     * @mbg.generated Mon Jan 02 19:26:45 GMT+08:00 2017
     */
    @UpdateProvider(type=ApplicationSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Application record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application
     *
     * @mbg.generated Mon Jan 02 19:26:45 GMT+08:00 2017
     */
    @Update({
        "update application",
        "set name = #{name,jdbcType=VARCHAR},",
          "code = #{code,jdbcType=VARCHAR},",
          "description = #{description,jdbcType=VARCHAR},",
          "base_path = #{basePath,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Application record);
    
    @Select("select * from application")
    public List<Application> searchApplication(ApplicationCondition applicationCondition);

    @Select("select * from application where code=#{code}")
	public Application findApplicationByCode(String code);
}