package cn.lcf.ims.mapper;

import org.springframework.stereotype.Repository;

import cn.lcf.ims.entity.Application;

public interface ApplicationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application
     *
     * @mbg.generated Mon Dec 19 17:36:36 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application
     *
     * @mbg.generated Mon Dec 19 17:36:36 CST 2016
     */
    int insert(Application record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application
     *
     * @mbg.generated Mon Dec 19 17:36:36 CST 2016
     */
    int insertSelective(Application record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application
     *
     * @mbg.generated Mon Dec 19 17:36:36 CST 2016
     */
    Application selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application
     *
     * @mbg.generated Mon Dec 19 17:36:36 CST 2016
     */
    int updateByPrimaryKeySelective(Application record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application
     *
     * @mbg.generated Mon Dec 19 17:36:36 CST 2016
     */
    int updateByPrimaryKey(Application record);
    
}